#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 11 14:10:59 2019

@author: timur
"""



from mpl_toolkits import mplot3d
import matplotlib.pyplot as plt
import numpy as np
import os
import tempfile
import scipy.stats as st
import pyabc as pa
import pandas as pd
import support_th as sth
import bioch_sim as bs
import glob


#s = bs.get_exmpl_sim("CoTrSplicing")

k1 = 0.03
k2 =0.02
k3 = 1/(1/k1 + 1/k2)

s = bs.SimParam("test", 300, 1001,
                {"k1":k1, "k2":k2, "k3":k3},
                {"A1":100, "A2":100})

s.add_reaction("A1*k1", {"A1":-1, "B":1})
s.add_reaction("B*k2", {"B":-1, "C1":1})
s.add_reaction("A2*k3", {"A2":-1, "C2":1})
c1s = []
c2s = []
bbs = []
for i in range(100):
    s.simulate()
    c1s.append(s.get_res_col("C1"))
    c2s.append(s.get_res_col("C2"))
    bbs.append(s.get_res_col("B"))
c1s = np.array(c1s)    
c2s = np.array(c2s)
bbs = np.array(bbs)
c1_mean = c1s.mean(axis=0)
c2_mean = c2s.mean(axis=0)
b_mean = bbs.mean(axis=0)

plt.plot(c1_mean, label = "C1")
plt.plot(c2_mean, label = "C2")                   
plt.plot(b_mean, label = "B")
plt.legend()

